// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using beautyTechAPI.Data;

#nullable disable

namespace beautyTechAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241024023651_Migration25")]
    partial class Migration25
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("beautyTechAPI.Models.Cliente", b =>
                {
                    b.Property<int>("ID_CLIENTE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_CLIENTE"));

                    b.Property<string>("CABELO_CLIENTE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CPF_CLIENTE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DT_CADASTRO")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DT_NASCIMENTO_CLIENTE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("EMAIL_CLIENTE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("ESTADO_CIVIL_CLIENTE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NM_CLIENTE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PELE_CLIENTE")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID_CLIENTE");

                    b.ToTable("BT_K_CLIENTE");
                });

            modelBuilder.Entity("beautyTechAPI.Models.Empresa", b =>
                {
                    b.Property<int>("ID_EMPRESA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_EMPRESA"));

                    b.Property<string>("CNPJ_EMPRESA")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DESC_EMPRESA")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NM_EMPRESA")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ID_EMPRESA");

                    b.ToTable("BT_K_EMPRESA");
                });

            modelBuilder.Entity("beautyTechAPI.Models.HistoricoPesquisa", b =>
                {
                    b.Property<int>("ID_HISTORICO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_HISTORICO"));

                    b.Property<int>("ID_CLIENTE")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("ID_PRODUTO")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ID_HISTORICO");

                    b.HasIndex("ID_CLIENTE");

                    b.HasIndex("ID_PRODUTO");

                    b.ToTable("BT_K_HISTORICO_PESQUISA");
                });

            modelBuilder.Entity("beautyTechAPI.Models.Produto", b =>
                {
                    b.Property<int>("ID_PRODUTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PRODUTO"));

                    b.Property<string>("DESC_PRODUTO")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DT_CADASTRO")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DT_FAB_PRODUTO")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DT_VALIDADE")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("NM_PRODUTO")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<decimal>("VL_PRODUTO")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("ID_PRODUTO");

                    b.ToTable("BT_K_PRODUTO");
                });

            modelBuilder.Entity("beautyTechAPI.Models.HistoricoPesquisa", b =>
                {
                    b.HasOne("beautyTechAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ID_CLIENTE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("beautyTechAPI.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ID_PRODUTO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
